### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by poko-loco** [AnKing-VIP/Editor-ProToolBox-Public#1]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-13 17:34:38

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 88, in wrapped_done
  File "aqt.progress", line 230, in finish
  File "aqt.progress", line 275, in _closeWin
TypeError: isdeleted() argument 1 must be PyQt6.sip.simplewrapper, not None

**Comment by poko-loco** [comment]
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Editor ProToolBox - Web importer, quick format, & media scraper⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/Users/dmitrymoi/Library/Application Support/Anki2/addons21/editor_pro_toolbox/__init__.py", line 12, in <module>
    from .browser import setup as setup_browser
  File "/Users/dmitrymoi/Library/Application Support/Anki2/addons21/editor_pro_toolbox/browser.py", line 30, in <module>
    from .note_processor import NoteProcessor
  File "/Users/dmitrymoi/Library/Application Support/Anki2/addons21/editor_pro_toolbox/note_processor.py", line 27, in <module>
    from ._vendor.jsonpath_rw.parser import parse  # type: ignore
  File "/Users/dmitrymoi/Library/Application Support/Anki2/addons21/editor_pro_toolbox/_vendor/jsonpath_rw/__init__.py", line 1, in <module>
    from .jsonpath import *
  File "/Users/dmitrymoi/Library/Application Support/Anki2/addons21/editor_pro_toolbox/_vendor/jsonpath_rw/jsonpath.py", line 3, in <module>
    import six
ModuleNotFoundError: No module named 'six'
⁩
